syntax = "proto3";

package pb;

import "google/api/annotations.proto";
import "rpc_create_user.proto";
import "rpc_update_user.proto";
import "rpc_login_user.proto";
import "rpc_verify_email.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "github.com/yuttana76/simbplebank/pb";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "Simple Bank API"
    version: "1.2"
    contact: {
      name: "smilecat studio"
      url: "https://github.com/yuttana76"
      email: "smilecat@gmail.com"
    };
    // license: {
    //   name: "BSD 3-Clause License"
    //   url: "https://github.com/grpc-ecosystem/grpc-gateway/blob/main/LICENSE"
    // }
    // extensions: {
    //   key: "x-something-something"
    //   value: {string_value: "yadda"}
    // }
  };
};

// The simple bank service definition.
service SimpleBank {
    // Create user RPC
    rpc CreateUser (CreateUserRequest) returns (CreateUserResponse) {
        option (google.api.http) = {
            post: "/v1/create_user"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            description: "Use this API to crete a new user"
            summary: "Create new user."
            tags: "users"
        };
    }
    // Update user RPC
    rpc UpdateUser (UpdateUserRequest) returns (UpdateUserResponse) {
        option (google.api.http) = {
            patch: "/v1/update_user"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            description: "Use this API to update an existing user"
            summary: "Update user."
            tags: "users"
        };
    }
    // Login user RPC
    rpc LoginUser (LoginUserRequest) returns (LoginUserResponse) {
        option (google.api.http) = {
            post: "/v1/login_user"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            description: "Use this API to login an existing user"
            summary: "Login user."
            tags: ["users"]
        };
    }
    // Verify email RPC
    rpc VerifyEmail (VerifyEmailRequest) returns (VerifyEmailResponse) {
        option (google.api.http) = {
            get: "/v1/verify_email"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            description: "Use this API to verify an existing user"
            summary: "Verify email."
            tags: ["users"]
        };
    }
}