// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service_simple_bank.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_simple_bank_proto protoreflect.FileDescriptor

const file_service_simple_bank_proto_rawDesc = "" +
	"\n" +
	"\x19service_simple_bank.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x15rpc_create_user.proto\x1a\x15rpc_update_user.proto\x1a\x14rpc_login_user.proto\x1a\x16rpc_verify_email.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xf1\x04\n" +
	"\n" +
	"SimpleBank\x12\x95\x01\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"X\x92A;\n" +
	"\x05users\x12\x10Create new user.\x1a Use this API to crete a new user\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12\x98\x01\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"[\x92A>\n" +
	"\x05users\x12\fUpdate user.\x1a'Use this API to update an existing user\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/update_user\x12\x92\x01\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"X\x92A<\n" +
	"\x05users\x12\vLogin user.\x1a&Use this API to login an existing user\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_user\x12\x9a\x01\n" +
	"\vVerifyEmail\x12\x16.pb.VerifyEmailRequest\x1a\x17.pb.VerifyEmailResponse\"Z\x92A?\n" +
	"\x05users\x12\rVerify email.\x1a'Use this API to verify an existing user\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/verify_emailB\x85\x01\x92A]\x12[\n" +
	"\x0fSimple Bank API\"C\n" +
	"\x0fsmilecat studio\x12\x1chttps://github.com/yuttana76\x1a\x12smilecat@gmail.com2\x031.2Z#github.com/yuttana76/simbplebank/pbb\x06proto3"

var file_service_simple_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),   // 0: pb.CreateUserRequest
	(*UpdateUserRequest)(nil),   // 1: pb.UpdateUserRequest
	(*LoginUserRequest)(nil),    // 2: pb.LoginUserRequest
	(*VerifyEmailRequest)(nil),  // 3: pb.VerifyEmailRequest
	(*CreateUserResponse)(nil),  // 4: pb.CreateUserResponse
	(*UpdateUserResponse)(nil),  // 5: pb.UpdateUserResponse
	(*LoginUserResponse)(nil),   // 6: pb.LoginUserResponse
	(*VerifyEmailResponse)(nil), // 7: pb.VerifyEmailResponse
}
var file_service_simple_bank_proto_depIdxs = []int32{
	0, // 0: pb.SimpleBank.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.SimpleBank.UpdateUser:input_type -> pb.UpdateUserRequest
	2, // 2: pb.SimpleBank.LoginUser:input_type -> pb.LoginUserRequest
	3, // 3: pb.SimpleBank.VerifyEmail:input_type -> pb.VerifyEmailRequest
	4, // 4: pb.SimpleBank.CreateUser:output_type -> pb.CreateUserResponse
	5, // 5: pb.SimpleBank.UpdateUser:output_type -> pb.UpdateUserResponse
	6, // 6: pb.SimpleBank.LoginUser:output_type -> pb.LoginUserResponse
	7, // 7: pb.SimpleBank.VerifyEmail:output_type -> pb.VerifyEmailResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_simple_bank_proto_init() }
func file_service_simple_bank_proto_init() {
	if File_service_simple_bank_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_verify_email_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_simple_bank_proto_rawDesc), len(file_service_simple_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_simple_bank_proto_goTypes,
		DependencyIndexes: file_service_simple_bank_proto_depIdxs,
	}.Build()
	File_service_simple_bank_proto = out.File
	file_service_simple_bank_proto_goTypes = nil
	file_service_simple_bank_proto_depIdxs = nil
}
